language: ruby
rvm:
  - 1.8.7
notifications:
  disabled: true
before_install:
 - python --version
 - echo "$GEM_HOME"
 - echo "$GEM_PATH"
 - gem env
 - gem list
 - cp -a /home/vagrant/.rvm/gems/ruby-1.8.7-p358/gems/ffi-1.0.11 /home/vagrant/ffi-1.0.11
 - gem uninstall -a ffi
 - gem install rubypython
 - diff -u /home/vagrant/.rvm/gems/ruby-1.8.7-p358/gems/ffi-1.0.11 /home/vagrant/ffi-1.0.11
 - ruby -e "require 'rubygems'; require 'rubypython'"
 - ruby -e "require 'rubygems'; require 'pygments.rb'"
