language: ruby
rvm:
  - 1.8.7
notifications:
  disabled: true
before_install:
 - python --version
 - echo "$GEM_HOME"
 - echo "$GEM_PATH"
 - gem env
 - gem list
 - gem install rubypython
 - ruby -e "require 'rubygems'; require 'rubypython'"
 - ruby -e "require 'rubygems'; require 'pygments.rb'"
