language: ruby
rvm:
  - 1.8.7
notifications:
  disabled: true
before_install:
 - gem install rubypython
 - python --version
 - echo "$GEM_HOME"
 - echo "$GEM_PATH"
 - gem env
 - gem list
 - grep -r -i ffi /home/vagrant/.rvm/gems/ruby-1.8.7-p358/gems/rubypython-0.5.3
 - ruby -e "require 'rubygems'; require 'rubypython'"
 - ruby -e "require 'rubygems'; require 'pygments.rb'"
