language: ruby
rvm:
  - 1.8.7
  - 1.9.3
notifications:
  disabled: true
before_install:
 - gem install ffi
 - gem install pygments.rb
 - python --version
 - gem list
 - ruby -e "require 'rubygems'; require 'ffi'"
 - ruby -e "require 'rubygems'; require 'rubypython'"
 - ruby -e "require 'rubygems'; require 'pygments.rb'"
