language: ruby
rvm:
  - 1.8.7
notifications:
  disabled: true
before_install:
 - gem install ffi
 - gem install pygments.rb
 - python --version
 - echo "$GEM_HOME"
 - echo "$GEM_PATH"
 - gem env
 - gem list
 - cat /home/vagrant/.rvm/rubies/ruby-1.8.7-p358/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb
 - ruby -e "require 'rubygems'; require 'ffi'" --debug
 - ruby -e "require 'rubygems'; require 'rubypython'" --debug
 - ruby -e "require 'rubygems'; require 'ffi'; require 'rubypython'"
 - ruby -e "require 'rubygems'; require 'pygments.rb'"
